# system setup
sudo: required

# setup language
language: go
go:
  - "1.11"

install:
  # download our task runner
  - go get github.com/AlecAivazis/run
  # install the ci dependencies
  - run install:ci

script:
  # install the dependencies
  - run install
  # generate and report the test coverage
  - run test:coverage

before_deploy:
  # build the binaries
  - run build

deploy:
  # only deploy on tagged releases
  on:
    tags: true
  # we need to push a github release with this tag
  provider: releases
  file:
    - "graphql-gateway_darwin_amd64"
    - "graphql-gateway_linux_amd64"
    - "graphql-gateway_windows_amd64"
  skip_cleanup: true
  api_key:
    secure: wBcfFBPmPOp28SOZweqccqM4hpd2h0oZUwBbVxchDHzQizhJ3sEb7SugzY2IqzwJjK+sSfTRQVbZdVtkzFLHHuTWXe7onELas4pSDTxdyKZnZQ0EpgdzZ/goTaDmG+MR9IDQz7wmaM4RtoQOJIlAAMOWUVIORSA77UbMqsXqMj0E/+L8tNY3itoSTNBuS/03CEUTiN956NuD1tAfi0hEMfy2z1xUC049Q0D9ZTDge9UEk6mb7t21/YvNEG2rgPxV53odDTSFn6Rvz2yj1jsa0eCA+fjPNphM+d0FsC24nk0j41cIroPFLF3jFfV1S5vTTjrYUzhgjSFwNxCoKA+CT9dEOfsnw8/pvTADLY600KvB0eD8GxGJfrsPb4iM2HU+YBXBA+4Sp5iqlgdQ2wzK1HWHac1s3LDM2pcgT2urW9v5LHzWn9mhojmPaaXc1NE6oebkQAxWBSx3J3rHdEUIff3466R80Kopui+kGcA12+W5bK7r7RjeMGzQdM3L97PLTmowF7NlLyR5UMYHBPxfK0+z5HuUdDyL3gRQQCmW0/0nfAJ5bGEj65pZFGvCGZFQ+yeI+R2qBzASeh0uhofH3YHOwenLP9A0HYUqfTjU4VPc3d7M7ISXKIXAzTXge27eMg7yrU1RGYSGCAHPbtzZPHjELbJ9uc0B8ycyI02R5Jo=
