name: Run Tests

on: [push]

jobs:
  build:

    runs-on: golang:latest
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install dependencies
      run: |
        go get -u github.com/alecaivazis/run
        run install:ci
